volumes:
  pg_data:

services:

  db:

    image: postgres
    container_name: db
    env_file: .env
    ports:
      - "5432:5432"

    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: aiogrambot
    env_file: .env
    depends_on:
      - db
    command: python aiogrambot/run.py