"""Update enum type

Revision ID: c71d32d93d37
Revises: fb97f1caa09b
Create Date: 2025-06-18 16:15:32.044323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71d32d93d37'
down_revision: Union[str, None] = 'fb97f1caa09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE measurement ADD VALUE IF NOT EXISTS 'g5'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
